### PR TITLE
Notifier - Add Deprecation Noitce for notifier - AGJS-281

### PR DESCRIPTION
**Pull request by lholmquist**
Adding the deprecation notice on Notifier

### CODE REVIEW

**Comment by lholmquist** [comment]
@lfryc @abstractj mind just taking a gander at this

**Comment by lfryc** [comment]
@lholmquist should we change status of Notifier API from Stable to Deprecated?

https://github.com/aerogear/aerogear-js/blob/master/src/notifier/aerogear.notifier.js#L18

**Comment by lholmquist** [comment]
@lfryc didn't i add the deprecated thingy here:  https://github.com/lholmquist/aerogear-js/blob/deprecate-notifier/src/notifier/aerogear.notifier.js#L18  ?

**Comment by lfryc** [comment]
In the generated Docs (bellow) it is little bit lost though, but let's keep it consistent as you deprecate usually.

Deprecation

**Comment by lholmquist** [comment]
@lfryc i totally forgot that we could use the @stable thingy,  so i added that also,  not as hidden

**Comment by lfryc** [comment]
yea, looks good :+1:

**Comment by lfryc** [comment]
:rocket: landed: https://github.com/aerogear/aerogear-js/commit/967f52e855e84808c4bfcbbb6cce6582f36fac9c

**Comment by matzew** [comment]
@lfryc @lholmquist what's the plan for the actual removal ? Do we have a JIRA for that ?

**Comment by lholmquist** [comment]
@matzew since this had "Stable" parts, we would need to wait until a 3.0 to completely remove it,  I'll add a JIRA.

There are some parts that were marked as experimental which could be removed sooner,  but that could be up for debate

**Comment by lholmquist** [comment]
Here is the JIRA,  https://issues.jboss.org/browse/AGJS-284

**Comment by matzew** [comment]
ok, thanks!

On Mon, Feb 23, 2015 at 5:38 PM, Lucas Holmquist <notifications@github.com>
wrote:

> Here is the JIRA, https://issues.jboss.org/browse/AGJS-284
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-js/pull/164#issuecomment-75578674>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request closed without merging**
