### PR TITLE
Diff sync client

### PR DESCRIPTION
**Pull request by lholmquist**
Initial addition the Diff Sync Client and Engines to interact with the Sync Server for the Alpha.1 release.

The code here is basically the code that is in the js cookbook, https://github.com/aerogear/aerogear-js-cookbook/tree/diff-sync-json-patch/diff-sync

If all looks good,  i would like to squash these commits before merging into master

### CODE REVIEW

**Comment by lholmquist** [comment]
@danbev @cvasilak @abstractj @sebastienblanc @matzew @danielpassos @qmx @secondsun @edewit @lfryc @corinnekrych 

if you peeps wouldn't mind taking a look,  although if you have seen the cookbook,  you should be familiar with it :)

**Comment by corinnekrych** [comment]
:eyes:

**Comment by corinnekrych** [comment]
@lholmquist 
When trying it on cookbook, I had:
1. one warning when running: ember server
 "Could not find watchman, falling back to NodeWatcher for file system events"
looks like it's related to https://github.com/ember-cli/ember-cli/issues/2703
after installing watchman the warning disappears
2. although netty-server is running I run into:
 WebSocket connection to 'ws://localhost:7777/sync' failed: WebSocket is closed before the connection is established.
when trying to connect...
sth obvious i missed?

**Comment by lfryc** [comment]
Great job, @lholmquist 

Few small issues:

1. I'm missing a link between `diff-sync` cookbook and `aerogear-sync-server` (I'm aware of where it is located, but others don't have to)

2. `docs` can't be build because of empty `@example` sections

I like the Ember example, trying to write the Ionic/Angular version as well so they we see whether it is as easy there.

**Comment by danbev** [comment]
:+1:

**Comment by lholmquist** [comment]
@lfryc let me remove those @example parts,  we can add them later

and i'll add a link in the cookbook to the sync server repo

Thanks for reviewing

**Comment by danbev** [comment]
@lholmquist Is this PR for https://issues.jboss.org/browse/AGJS-275 ? Just trying to go through JIRA and see what task remain.

**Comment by lholmquist** [comment]
@danbev one of many i think :),  i'm about to merge this,  so i'll search and close all the related ones

**Comment by danbev** [comment]
@lholmquist awesome, thanks.

**Comment by lholmquist** [comment]
@danbev for consistency,  it was this one,  https://issues.jboss.org/browse/AGJS-124

**Comment by lholmquist** [comment]
landed here:  1eac83d6da75f59db53884d65a9bfc1ac75e3e6f

**Pull request closed without merging**
