### PR TITLE
update README with Project Info

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AEROGEAR-1591

### CODE REVIEW

**Comment by lfryc** [comment]
Hmm maybe linking Documentation to https://aerogear.org/javascript/ would be better

**Comment by lfryc** [comment]
@lholmquist could you please review?

**Comment by lholmquist** [comment]
:+1:

**Comment by lfryc** [comment]
awesome, I will update also rest of the repos

**Pull request merged**
