### PR TITLE
UnifiedPush - Remove AeroGear.ajax and merge it with the UnifiedPush SDK...

### PR DESCRIPTION
**Pull request by lholmquist**
... - AGJS-279

### CODE REVIEW

**Comment by matzew** [comment]
@sebastienblanc mind doing a review ?

**Comment by lfryc** [comment]
I'm :eyes: it

**Comment by lfryc** [comment]
:+1: for merging

**Comment by matzew** [comment]
+1

On Wednesday, February 4, 2015, Lukáš Fryč <notifications@github.com> wrote:

> [image: :+1:] for merging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-js/pull/161#issuecomment-72836077>.
>


-- 
Sent from Gmail Mobile

**Comment by lfryc** [comment]
merged https://github.com/aerogear/aerogear-js/commit/6356c1628e3cb884e81654d3029499fc149601b8

**Pull request merged**
